theme: jekyll-theme-minimal
url:  "https://dirkscholte.github.io"
twitter_username: dirkscholte
github_username:  dirkscholte
linkedin_username: dirkscholte
ads_link: "https://ui.adsabs.harvard.edu/search/q=%20author%3A%22Scholte%2C%20Dirk%22&sort=date%20desc%2C%20bibcode%20desc&p_=0"
