theme: jekyll-theme-minimal
title: Dirk Scholte
description: PhD Candidate at UCL
logo: https://media-exp1.licdn.com/dms/image/C4D03AQGFLLrvCTg5Mw/profile-displayphoto-shrink_400_400/0/1602506139266?e=1647475200&v=beta&t=5l6UI7lz3mmj1gkjjxB4VQseFWwB15uiVB-FGoQvXcc
show_downloads: false
markdown: kramdown
