theme: jekyll-theme-minimal
url: https://dirkscholte.github.io
logo: https://media-exp1.licdn.com/dms/image/C4D03AQGFLLrvCTg5Mw/profile-displayphoto-shrink_200_200/0/1602506139266?e=1657152000&v=beta&t=CBstYmCgXwgwpqnc9vMWp0_Zz1l4PQ0xp2_yFgF3Y0A
show_downloads: false
markdown: kramdown
