theme: jekyll-theme-minimal
url: https://dirkscholte.github.io
description: [LinkedIn](https://www.linkedin.com/in/dirk-scholte/) \n [Twitter](https://twitter.com/DirkScholte) \n [Contact](https://www.ucl.ac.uk/astrophysics/dirk-scholte-phd-student)
logo: https://media-exp1.licdn.com/dms/image/C4D03AQGFLLrvCTg5Mw/profile-displayphoto-shrink_400_400/0/1602506139266?e=1647475200&v=beta&t=5l6UI7lz3mmj1gkjjxB4VQseFWwB15uiVB-FGoQvXcc
show_downloads: false
markdown: kramdown
